# Travis config for Chef testing
language: ruby
gemfile:
  - test/support/Gemfile

# specify ruby version to run this under (is this necessary?)
rvm:
  - 2.1.0

script:
  - bundle exec rake foodcritic
  - bundle exec rake knife
