# Travis config for Chef testing

language: ruby
gemfile:
  - test/support/Gemfile

env:
  global:
    - ORGNAME=tensqft
    - secure: "ackARWVgvFzdMeY5Hp1iVZW0OWl2Lh2iUnNbLnT/XRLPZz6/Y/ecnCtJrKRVVUtXr0O2YkIvPUc6f8h+z3sHOkMi3sLHLg9Hf35Tuy4+Gp5t71X3pA1lIoy/yXBPcxvud/FeIHPNV1A2sJDFzMzSPyu0tCIoImX5HR6c5p+GPXA="

# specify ruby version to run this under (is this necessary?)
rvm:
  - 2.1.0

script:
  - bundle exec rake foodcritic
  - bundle exec rake knife

after_success: 
  - if [ $TRAVIS_BRANCH == 'master' ] ; then
        openssl aes-256-cbc -k "$chef_validator_pw" -in .chef/chef_validator_pem.enc -out .chef/$ORGNAME-validator.pem -d
        bundle exec rake deploy;
    fi
